### ISSUE TITLE
Sample App Crashes

### ISSUE THREAD

**Issue by aniket08485786** [Instamojo/android-sdk-sample-app#10]
App Crashes after clicking Pay button

Here is the Log

08-03 01:08:45.202 20000-20000/com.instamojo.androidsdksample D/AppTracker: App Event: stop
08-03 01:08:45.288 20000-20000/com.instamojo.androidsdksample D/PaymentDetailsActivity: Inflated XML
08-03 01:08:45.288 20000-20000/com.instamojo.androidsdksample D/PaymentDetailsActivity: looking for Order object...
08-03 01:08:45.289 20000-20000/com.instamojo.androidsdksample D/PaymentDetailsActivity: Found order Object. Starting PaymentOptionsFragment
08-03 01:08:45.303 20000-20000/com.instamojo.androidsdksample D/PaymentDetailsActivity: Loading Fragment - ChoosePaymentOption
08-03 01:08:45.317 20000-20000/com.instamojo.androidsdksample D/PaymentDetailsActivity: Loaded Fragment - ChoosePaymentOption
08-03 01:08:45.334 20000-20000/com.instamojo.androidsdksample D/ChoosePaymentOption: Inflated XML
08-03 01:08:45.336 20000-20000/com.instamojo.androidsdksample D/PaymentDetailsActivity: Setting title for Toolbar
08-03 01:08:45.336 20000-20000/com.instamojo.androidsdksample D/AppTracker: App Event: start
08-03 01:08:45.343 20000-20000/com.instamojo.androidsdksample D/AbstractTracker: Event success
08-03 01:08:45.367 20000-20000/com.instamojo.androidsdksample D/PaymentDetailsActivity: Inflated Options Menu
08-03 01:08:45.373 20000-20000/com.instamojo.androidsdksample D/AbstractTracker: Event success
08-03 01:08:48.312 20000-20000/com.instamojo.androidsdksample D/ChoosePaymentOption: Starting CardForm
08-03 01:08:48.324 20000-20000/com.instamojo.androidsdksample D/PaymentDetailsActivity: Loading Fragment - CardForm
08-03 01:08:48.325 20000-20000/com.instamojo.androidsdksample D/PaymentDetailsActivity: Loaded Fragment - CardForm
08-03 01:08:48.393 20000-20000/com.instamojo.androidsdksample D/CardForm: Inflated XML
08-03 01:08:48.395 20000-20000/com.instamojo.androidsdksample D/PaymentDetailsActivity: Setting title for Toolbar
08-03 01:09:00.916 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: sendKeyEvent on inactive InputConnection
08-03 01:09:02.059 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: sendKeyEvent on inactive InputConnection
08-03 01:09:02.461 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: sendKeyEvent on inactive InputConnection
08-03 01:09:03.361 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: sendKeyEvent on inactive InputConnection
08-03 01:09:04.073 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: sendKeyEvent on inactive InputConnection
08-03 01:09:04.793 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: sendKeyEvent on inactive InputConnection
08-03 01:09:05.504 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: sendKeyEvent on inactive InputConnection
08-03 01:09:11.554 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
08-03 01:09:11.554 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
08-03 01:09:11.568 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
08-03 01:09:11.569 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
08-03 01:09:11.582 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
08-03 01:09:13.227 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: sendKeyEvent on inactive InputConnection
08-03 01:09:15.071 20000-20000/com.instamojo.androidsdksample W/IInputConnectionWrapper: sendKeyEvent on inactive InputConnection
08-03 01:09:24.313 20000-20000/com.instamojo.androidsdksample D/CardForm: Checking Out
08-03 01:09:24.571 20000-20008/com.instamojo.androidsdksample W/art: Suspending all threads took: 5.242ms
                                                                     
                                                                     [ 08-03 01:09:26.406 20000:24104 E/         ]
                                                                     Error while making Juspay request - Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
                                                                     
                                                                     --------- beginning of crash
08-03 01:09:26.412 20000-24104/com.instamojo.androidsdksample E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                                Process: com.instamojo.androidsdksample, PID: 20000
                                                                                java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                                    at android.os.Handler.<init>(Handler.java:200)
                                                                                    at android.os.Handler.<init>(Handler.java:114)
                                                                                    at android.widget.Toast$TN.<init>(Toast.java:345)
                                                                                    at android.widget.Toast.<init>(Toast.java:101)
                                                                                    at android.widget.Toast.makeText(Toast.java:259)
                                                                                    at android.widget.Toast.makeText(Toast.java:286)
                                                                                    at com.instamojo.android.fragments.CardForm$3.onFinish(CardForm.java:239)
                                                                                    at com.instamojo.android.network.Request$1.onResponse(Request.java:138)
                                                                                    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                                    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                    at java.lang.Thread.run(Thread.java:818)
08-03 01:09:26.412 20000-24104/com.instamojo.androidsdksample E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
08-03 01:09:26.412 20000-24104/com.instamojo.androidsdksample D/AppTracker: App Event: crash
08-03 01:09:26.418 20000-24104/com.instamojo.androidsdksample E/AbstractTracker: mTrackerAsyncQueryHandler is null
08-03 01:09:26.460 20000-20000/com.instamojo.androidsdksample D/AppTracker: App Event: stop
08-03 01:09:26.470 20000-20000/com.instamojo.androidsdksample E/DeviceManagerUtil: RunningAppProcessInfo is null
08-03 01:09:26.470 20000-24104/com.instamojo.androidsdksample I/Process: Sending signal. PID: 20000 SIG: 9

**Comment by saich** [comment]
@vedhavyas: Can you refer to which commit fixed this issue?
