### ISSUE TITLE
Regarding READ_PHONE_STATE permission?

### ISSUE THREAD

**Issue by achinverma** [Instamojo/android-sdk-sample-app#16]
Hi ,
i am using this demo for payments but i have one query , is it necessary to use below permission and if i remove this then what will happen with my code? i mean will i got any error?  
`<uses-permission android:name="android.permission.READ_PHONE_STATE" />`

**Comment by vedhavyas** [comment]
The permission is required for juspay sdk. As far I remember, it's optional and u can remove it. I would say remove it and make a transaction
