### ISSUE TITLE
Juspaybrowser integration error

### ISSUE THREAD

**Issue by GOHILCHIRAG** [Instamojo/android-sdk-sample-app#17]
I am getting the error after successfully integrating this instamojo sdk.
"in.juspay.godel.ui.JuspayBrowserFragment: INTEGRATION ERROR - Payment Status not sent"
this error is shown logcat.
Please help.

**Comment by KEliz** [comment]
did you find a solution?
I am also getting the exact same error.

**Comment by vedhavyas** [comment]
You do not have to worry about that warning since the payment status is sent through the server.

**Comment by amitprasad0** [comment]
Failed to resolve: in.juspay:godel:0.6.18.1423

**Comment by saich** [comment]
This is a warning, and no action is needed. Nothing to worry about.
