### ISSUE TITLE
Instamojo PG Not Working in Android 9.0 (Pie)

### ISSUE THREAD

**Issue by husenmemon** [Instamojo/android-sdk-sample-app#28]
I have integrated Instamojo Payment Gateway in Android app but it is showing blank page when using the app on Android 9.0 (Pie). I thought its temporary issue and will get fixed soon but since the launch of Android Pie till today, this issue isn't yet fixed. Please devs, look in to it and fix it ASAP!

**Comment by vijithv** [comment]
@husenmemon Thanks for notifying. The sample app is now part of the SDK repo itself. Updated the readme: https://github.com/Instamojo/android-sdk-sample-app/blob/master/ReadMe.md
